version: '3'
services:
  dpi:
    build:
      context: .
      dockerfile: Dockerfile
    image: captcha:base
    working_dir: /code
    volumes:
      - .:/code
    command: python3 digital_processing_image_approach.py

  generate-captchas:
    build:
      context: .
      dockerfile: Dockerfile
    image: captcha:base
    working_dir: /code
    volumes:
      - .:/code
    command: python3 generate_captchas.py

  deep-learning:
    build:
      context: .
      dockerfile: Dockerfile-deep
    working_dir: /code
    volumes:
      - .:/code
      - /dev/nvidia0:/dev/nvidia0
    command: python3 deep_learning.py
